solar_train_from_history:
  name: Train Solar Power ML Model from historical data
  description: Train the solar power prediction model
  fields:
    days_back:
      name: Days Back
      description: Number of days to look back for training data
      required: false
      default: 60
      example: 60
      selector:
        number:
          min: 1
          mode: box
    hours_offset:
      name: Hours Offset
      description: Number of hours offset for training data
      required: false
      default: 1
      example: 1
      selector:
        number:
          min: 1
          mode: box

solar_train_from_csv:
  name: Train Solar Power ML Model from CSV
  description: Train the solar power prediction model from PV Power values stored in CSV
  fields:
    csv_file:
      name: CSV File Name
      description: File name of the CSV file containing PV Power values
      required: true
      default: 'pv_power.csv'
      example: 'pv_power.csv'
      selector:
        text:
          mode: box


solar_predict:
  name: Predict Solar Power
  description: Predict solar power output for a given time period
  fields:
    days_back:
      name: Days Back
      description: Days back for prediction period
      required: true
      default: 3
      example: 3
      selector:
        number:
          min: 0
          mode: box
    days_forward:
      name: Days Forward
      description: Days forward for prediction period
      required: true
      default: 7
      example: 7
      selector:
        number:
          min: 0
          mode: box


consumption_train_from_history:
  name: Train power consumption ML Model from historical data
  description: Train the power consumption prediction model
  fields:
    days_back:
      name: Days Back
      description: Number of days to look back for training data
      required: false
      default: 60
      example: 60
      selector:
        number:
          min: 1
          mode: box
    hours_offset:
      name: Hours Offset
      description: Number of hours offset for training data
      required: false
      default: 1
      example: 1
      selector:
        number:
          min: 1
          mode: box

consumption_train_from_csv:
  name: Train Power Consumption ML Model from CSV
  description: Train the power consumption prediction model from PV Power values stored in CSV
  fields:
    csv_file:
      name: CSV File Name
      description: File name of the CSV file containing Power Consumption values
      required: true
      default: 'pv_power.csv'
      example: 'pv_power.csv'
      selector:
        text:
          mode: box


consumption_predict:
  name: Predict Power Consumption
  description: Predict power consumption for a given time period
  fields:
    days_back:
      name: Days Back
      description: Days back for prediction period
      required: true
      default: 3
      example: 3
      selector:
        number:
          min: 0
          mode: box
    days_forward:
      name: Days Forward
      description: Days forward for prediction period
      required: true
      default: 7
      example: 7
      selector:
        number:
          min: 0
          mode: box

battery_predict:
  name: Predict Battery Capacity
  description: Predict battery capacity for a given days ahead
  fields:
    days_forward:
      name: Days Forward
      description: Days forward for prediction period
      required: true
      default: 7
      example: 7
      selector:
        number:
          min: 0
          mode: box